name: PolygonTriangulation-Tests

on:
  pull_request:
    branches: main
  workflow_dispatch:
    branches: main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v5
      with:
        ref: refs/heads/${{ github.head_ref }}

    - name: Build Program
      run: |
        make all

    - name: Build Tests
      run: |
        make tests

    - name: Run Unit Tests
      run: |
        ./RunUnitTests.exe

    - name: Run Regression Tests
      run: |
        ./RunRegressionTests.exe

